import Head from "next/head";
import Banner from "../components/Banner";
import styles from "../styles/Home.module.css";

export default function Home() {
	const handleBannerClick = () => {
		console.log("clicked");
	};
	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Shops</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Banner
				buttonText="View stores nearby"
				handleOnClick={handleBannerClick}
			/>
		</div>
	);
}
